apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
    annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    name: ingress-service
spec: 
    rules: 
    - 
        host: kubelicious.com
        http: 
        paths: 
            - 
            backend: 
                serviceName: client-cluster-ip-service
                servicePort: 3000
            path: /?(.*)
            - 
            backend: 
                serviceName: server-cluster-ip-service
                servicePort: 5000
            path: /api/?(.*)
    - 
        host: www.kubelicious.com
        http: 
        paths: 
            - 
            backend: 
                serviceName: client-cluster-ip-service
                servicePort: 3000
            path: /?(.*)
            - 
            backend: 
                serviceName: server-cluster-ip-service
                servicePort: 5000
            path: /api/?(.*)
    tls: 
    - 
        hosts: 
        - kubelicious.com
        - www.kubelicious.com
        secretName: kubelicious-com-tls
